[phases.setup]
nixPkgs = ["nodejs_22", "bash"]

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd frontend && npm install",
  "chmod +x start.sh"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "bash start.sh"